services:
  - type: web
    name: flask-getdata-app
    env: python
    plan: free
    region: oregon
    branch: main

    buildCommand: |
      echo "ðŸ”§ Installing requirements..."
      pip install -r requirements.txt

    startCommand: |
      echo "ðŸš€ Starting Gunicorn..."
      gunicorn app:app --workers 1 --threads 2 --timeout 600 --bind 0.0.0.0:$PORT


