services:
  - type: web
    name: flask-getdata-app
    env: python
    plan: free
    region: oregon
    branch: main

    buildCommand: |
      echo "ðŸ”§ Installing requirements..."
      pip install -r requirements.txt

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
